version: 0.2

# same as 
# <phases>
#   <install>
#     <runtime-versions>
#       <node.js>8</node.js>
#       <commands></commands
#     </runtime-versions>
#   </install>
# </phases>
env:
  variables:
    REACT_APP_ENV: "prod"
phases:
  install:
    runtime-versions:
      node.js: 12
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'project-1-JustinM/build'